// // export const IMG_CDN_URL=
// // "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

// // Image CDN URL for Restaurant card
// export const IMG_CDN_URL =
//   "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";


// export const restaurantList = [
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "74453",
//         name: "Domino's Pizza",
//         uuid: "87727dbd-7f2b-4857-9763-359624165845",
//         city: "21",
//         area: "Athwa",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "bz9zkh2aqywjhpankb07",
//         cuisines: ["Pizzas"],
//         tags: [],
//         costForTwo: 40000,
//         costForTwoString: "₹400 FOR TWO",
//         deliveryTime: 45,
//         minDeliveryTime: 45,
//         maxDeliveryTime: 45,
//         slaString: "45 MINS",
//         lastMileTravel: 0,
//         slugs: {
//           restaurant: "dominos-pizza-majura-nondh-test_surat",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "Shop 32 To 35, Sheetal Shopping Square,Near Lb Turning Point, Bhatar Road,MAJURA NONDH, Surat,GUJARAT-395001",
//         locality: "Bhatar Road",
//         parentId: 2456,
//         unserviceable: false,
//         veg: true,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "74453",
//           deliveryTime: 45,
//           minDeliveryTime: 45,
//           maxDeliveryTime: 45,
//           lastMileTravel: 0,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.0",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "410476",
//         name: "The Brooklyn Creamery - Healthy Ice Cream",
//         uuid: "82e23b48-b6bd-4ee0-9746-06737ec062b0",
//         city: "21",
//         area: "althan bhatar",
//         totalRatingsString: "100+ ratings",
//         cloudinaryImageId: "ldtibwymvzehvmdwl8la",
//         cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 31,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 40,
//         slaString: "30-40 MINS",
//         lastMileTravel: 6.300000190734863,
//         slugs: {
//           restaurant: "the-brooklyn-creamery-low-cal-ice-cream-adajan-fc-adajan",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "C paiki, Chalta no. 23, Guru Ashish Building, Ground Floor, Opp Kotyark Nagar, Rander Road, Surat 395005",
//         locality: "Adajan FC",
//         parentId: 236673,
//         unserviceable: true,
//         veg: true,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "6.3 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "410476",
//           deliveryTime: 31,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 40,
//           lastMileTravel: 6.300000190734863,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.4",
//         totalRatings: 100,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "81094",
//         name: "Richie Rich Juices & Shakes",
//         uuid: "40b0b55b-e9af-43e7-aeae-be1b012d0b1d",
//         city: "21",
//         area: "Athwa",
//         totalRatingsString: "500+ ratings",
//         cloudinaryImageId: "nyp7yrzwc1dc2xqfkydk",
//         cuisines: ["Ice Cream"],
//         tags: [],
//         costForTwo: 25000,
//         costForTwoString: "₹250 FOR TWO",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 40,
//         slaString: "30-40 MINS",
//         lastMileTravel: 5.599999904632568,
//         slugs: {
//           restaurant: "juices-shakes-by-richie-rich-athwa-athwa",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "Richie Rich Building , Opposite Golden Square Complex, Parle Point, Athwa, Surat",
//         locality: "Parle Point",
//         parentId: 771,
//         unserviceable: true,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "5.5 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "81094",
//           deliveryTime: 30,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 40,
//           lastMileTravel: 5.599999904632568,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.9",
//         totalRatings: 500,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "311443",
//         name: "Siddhi Icecream & Thick Shake",
//         uuid: "1ca3e8c2-e5da-4b59-8f7e-868991cb40b7",
//         city: "21",
//         area: "Nanpura",
//         totalRatingsString: "100+ ratings",
//         cloudinaryImageId: "spd3y5gok3vvwqulgmda",
//         cuisines: ["Ice Cream", "Juices", "Desserts", "Beverages"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 30,
//         minDeliveryTime: 25,
//         maxDeliveryTime: 35,
//         slaString: "25-35 MINS",
//         lastMileTravel: 3,
//         slugs: {
//           restaurant: "siddhi-icecream-athwa-athwa",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "siddhi icecream, Kadampally Society, Timaliawad, Nanpura, Surat, Gujarat, India",
//         locality: "Athwa",
//         parentId: 387846,
//         unserviceable: true,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "311443",
//           deliveryTime: 30,
//           minDeliveryTime: 25,
//           maxDeliveryTime: 35,
//           lastMileTravel: 3,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.5",
//         totalRatings: 100,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "307070",
//         name: "Pizza Pie",
//         uuid: "68598bcb-7460-4466-a8b2-113158c6cf8c",
//         city: "21",
//         area: "Nanpura",
//         totalRatingsString: "50+ ratings",
//         cloudinaryImageId: "bvr70adr30ejyr5ua79k",
//         cuisines: ["Pizzas"],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 37,
//         minDeliveryTime: 35,
//         maxDeliveryTime: 45,
//         slaString: "35-45 MINS",
//         lastMileTravel: 4,
//         slugs: {
//           restaurant: "pizza-pie-athwa-athwa",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "1/704 Sarang building, Nanpura New Rd, opposite river palace, near Ramji Mandir, Nanpura, Surat, Gujarat",
//         locality: "Nanpura",
//         parentId: 158854,
//         unserviceable: true,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "4 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "307070",
//           deliveryTime: 37,
//           minDeliveryTime: 35,
//           maxDeliveryTime: 45,
//           lastMileTravel: 4,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.2",
//         totalRatings: 50,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "76858",
//         name: "Feeling Hungry",
//         uuid: "45f9ea54-f3cf-4f6b-8d85-e3468657fe51",
//         city: "21",
//         area: "Athwa",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "oxsb5mr1xsmhnxhunjsc",
//         cuisines: ["Chinese", "North Indian", "Biryani"],
//         tags: [],
//         costForTwo: 2000,
//         costForTwoString: "₹20 FOR TWO",
//         deliveryTime: 35,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 40,
//         slaString: "30-40 MINS",
//         lastMileTravel: 3.700000047683716,
//         slugs: {
//           restaurant: "feeling-hungry-adajan-gam-adajan",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "GF shop no 1, Babubhai Chambers, Beside Sardar Bridge , Athwagate, surat",
//         locality: "Royal Residency, Adajan Gam",
//         parentId: 79237,
//         unserviceable: true,
//         veg: true,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3.7 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "76858",
//           deliveryTime: 35,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 40,
//           lastMileTravel: 3.700000047683716,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.2",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "617279",
//         name: "Malaxmi Fast Food",
//         uuid: "4848cb1b-b1c4-4a6e-9a6d-f96b781357db",
//         city: "21",
//         area: "Adajan",
//         totalRatingsString: "20+ ratings",
//         cloudinaryImageId: "agkm7cflq72tkualhstb",
//         cuisines: ["Fast Food", "Pizzas", "Snacks", "Beverages"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 44,
//         minDeliveryTime: 40,
//         maxDeliveryTime: 50,
//         slaString: "40-50 MINS",
//         lastMileTravel: 9.100000381469727,
//         slugs: {
//           restaurant: "mahalaxmi-fast-food-adajan-adajan-2",
//           city: "surat",
//         },
//         cityState: "21",
//         address: "shop no 15,palanpur food zone,opp.sai trith,pal gam suart",
//         locality: "Palanpur Food Zone",
//         parentId: 373635,
//         unserviceable: true,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "9.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "617279",
//           deliveryTime: 44,
//           minDeliveryTime: 40,
//           maxDeliveryTime: 50,
//           lastMileTravel: 9.100000381469727,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.0",
//         totalRatings: 20,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "469264",
//         name: "Dessert House",
//         uuid: "7a320917-c577-49cb-875a-1e585a3adbc1",
//         city: "21",
//         area: "Piplod",
//         totalRatingsString: "Too Few Ratings", // cloudinaryImageId,name,cuisines,id,avgRating
//         cloudinaryImageId: "jegpumsjcmomksbr2sxr",
//         cuisines: ["Desserts", "Ice Cream"],
//         tags: [],
//         costForTwo: 15000,
//         costForTwoString: "₹150 FOR TWO",
//         deliveryTime: 27,
//         minDeliveryTime: 25,
//         maxDeliveryTime: 35,
//         slaString: "25-35 MINS",
//         lastMileTravel: 6.199999809265137,
//         slugs: {
//           restaurant: "dessert-house-piplod-piplod",
//           city: "surat",
//         },
//         cityState: "21",
//         address:
//           "SHOP NO 2, MARVELLA CORRIDOR OPP. C B PATEL HEALTH CLUB V.I.P ROAD, VESU",
//         locality: "Piplod",
//         parentId: 71430,
//         unserviceable: true,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "FREE DELIVERY",
//           shortDescriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "",
//           shortDescriptionList: [
//             {
//               meta: "Free Delivery",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "FREE DELIVERY",
//               discountType: "FREE_DELIVERY",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [],
//           totalFees: 0,
//           message: "",
//           title: "",
//           amount: "",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "6.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "469264",
//           deliveryTime: 27,
//           minDeliveryTime: 25,
//           maxDeliveryTime: 35,
//           lastMileTravel: 6.199999809265137,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE_WITH_BANNER",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.5",
//         totalRatings: 0,
//         new: false,
//       },
//       subtype: "basic",
//     },
    
// ];

 export const swiggy_api_URL =
  "https://foodfire.onrender.com/api/restaurants?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING";

export const IMAGE_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill";

export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "73011",
      name: "KFC",
      uuid: "27ff4155-fe46-418e-9862-ab98953bf953",
      city: "22",
      area: "Anand Vihar Colony",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
      cuisines: ["American", "Snacks", "Biryani"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 6.199999809265137,
      slugs: {
        restaurant: "kfc-chukkuwala-chukkuwala",
        city: "dehradun",
      },
      cityState: "22",
      address:
        "KFC Restaurant, Khasra No 1281/1291, Opp Dr Manish Jain hospital, Chakrata road, Dehradun-248001",
      locality: "Clock Tower",
      parentId: 547,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=5698075~p=1~eid=00000185-8b09-7c92-0e51-a04b00dc0124",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "73011",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 6.199999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "542132",
      name: "Domnik Pizza",
      uuid: "f2ee37f5-9ab0-4903-9420-6cae020b0a38",
      city: "22",
      area: "Majra    Bansal Home",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "sboh9oor0cvp6ztsyhvj",
      cuisines: ["Pizzas", "Italian", "Fast Food", "Snacks", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: "domnik-pizza-patel-nagar-patel-nagar-2",
        city: "dehradun",
      },
      cityState: "22",
      address:
        "28/3 Sewala Chandravani Road, Arcedia Grant, Dehradun Rural, Dehradun, Uttarakhand",
      locality: "Patel Nagar",
      parentId: 22321,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      sla: {
        restaurantId: "542132",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "321517",
      name: "FOOD PLANET RESTAURANT",
      uuid: "899d5dd4-200a-48b2-a321-391bb9486ec2",
      city: "22",
      area: "Majra",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "ykboewqeoxnne8fgrnui",
      cuisines: ["Indian", "Chinese", "Tandoor", "Thalis", "Fast Food"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 0.699999988079071,
      slugs: {
        restaurant: "food-planet-restaurant-patel-nagar-patel-nagar",
        city: "dehradun",
      },
      cityState: "22",
      address:
        "157/11, Chandra Parisar Chandra Bani Rd, Ekta Enclave, Doon Enclave, Majra, Dehradun, Uttarakhand 248171",
      locality: "Patel Nagar",
      parentId: 81850,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      sla: {
        restaurantId: "321517",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 0.699999988079071,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "2.8",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "311806",
      name: "Burger King",
      uuid: "162a4dc4-50de-452a-82cf-751e18ac9952",
      city: "22",
      area: "Anand Vihar Colony",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "iqh7ew5ldfgvpd5dpz60",
      cuisines: ["Burgers", "American"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 6.300000190734863,
      slugs: {
        restaurant: "burger-king-chakrata-road-ballupur",
        city: "dehradun",
      },
      cityState: "22",
      address:
        "5/5,4/4 & 3/3, GROUND FLOOR, CHAKRATA ROAD, DEHRADUN, UTTRAKHAND",
      locality: "CHAKRATA ROAD",
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "60% off",
        shortDescriptionList: [
          {
            meta: "60% off | Use STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "60% off up to ₹120 | Use code STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "60% OFF",
        shortDescriptionList: [
          {
            meta: "Use STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "60% off up to ₹120 | Use code STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=5700193~p=4~eid=00000185-8b09-7c92-0e51-a04c00dc0405",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "311806",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 6.300000190734863,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.2",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "132460",
      name: "Annapurna Andhra Mess",
      uuid: "c6460418-904b-4371-9e04-0ce8b1b46cae",
      city: "22",
      area: "Dehradun",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "zw4qx2szsy9kbszk9n3d",
      cuisines: ["South Indian", "Biryani", "North Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant: "annapurna-andhra-mess-subhash-nagar-subhash-nagar",
        city: "dehradun",
      },
      cityState: "22",
      address:
        "keshav enclave sewla khurd chandrabani road behind uttranchal PG college",
      locality: "Patel Nagar",
      parentId: 33997,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "132460",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "496677",
      name: "Uncle Ji Restaurant",
      uuid: "e652ab57-22c2-4226-b5ea-a5caa26ee0f8",
      city: "22",
      area: "Patel Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "kx2ghnwagcnqjtmd5jbc",
      cuisines: ["North Indian", "Snacks", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "uncle-ji-restaurant-patel-nagar-patel-nagar",
        city: "dehradun",
      },
      cityState: "22",
      address: "348 santosh tower, majra road gram majra dehradun 248001",
      locality: "Patel Nagar",
      parentId: 298209,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "496677",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
];